using AutoMapper; using Microsoft.EntityFrameworkCore; using Mubi.Api.Data; using Mubi.Api.DTOs.Base; using Mubi.Api.DTOs.Create; using Mubi.Api.DTOs.Update; using Mubi.Api.Models; using Mubi.Api.Security; using Mubi.Api.Services.Interfaces;
namespace Mubi.Api.Services.Implementations;
public class UsuarioService : IUsuarioService
{
 private readonly MubiDbContext _context; private readonly IMapper _mapper; public UsuarioService(MubiDbContext context, IMapper mapper){_context=context;_mapper=mapper;}
 public async Task<IEnumerable<UsuarioResponseDto>> GetAllAsync(){var data=await _context.Usuarios.Include(x=>x.Rol).OrderByDescending(x=>x.IdUsuario).ToListAsync(); return _mapper.Map<IEnumerable<UsuarioResponseDto>>(data);} 
 public async Task<UsuarioResponseDto?> GetByIdAsync(int id){var e=await _context.Usuarios.Include(x=>x.Rol).FirstOrDefaultAsync(x=>x.IdUsuario==id); return e==null?null:_mapper.Map<UsuarioResponseDto>(e);} 
 public async Task<UsuarioResponseDto> CreateAsync(CreateUsuarioDto dto){ if(await _context.Usuarios.AnyAsync(x=>x.Correo==dto.Correo)) throw new Exception("Ya existe un usuario con ese correo."); var e=_mapper.Map<Usuario>(dto); e.Contrasena=PasswordHasher.Hash(dto.Contrasena); e.FechaRegistro=DateTime.Now; e.Estado="activo"; _context.Usuarios.Add(e); await _context.SaveChangesAsync(); e=await _context.Usuarios.Include(x=>x.Rol).FirstAsync(x=>x.IdUsuario==e.IdUsuario); return _mapper.Map<UsuarioResponseDto>(e);} 
 public async Task<UsuarioResponseDto?> UpdateAsync(int id, UpdateUsuarioDto dto){ var e=await _context.Usuarios.Include(x=>x.Rol).FirstOrDefaultAsync(x=>x.IdUsuario==id); if(e==null) return null; e.Nombre=dto.Nombre; e.Apellido=dto.Apellido; e.Estado=(dto.Estado ?? "activo").Trim().ToLower(); e.IdRol=dto.IdRol; await _context.SaveChangesAsync(); e=await _context.Usuarios.Include(x=>x.Rol).FirstAsync(x=>x.IdUsuario==id); return _mapper.Map<UsuarioResponseDto>(e);} 
 public async Task<bool> DeleteAsync(int id){ var e=await _context.Usuarios.FindAsync(id); if(e==null) return false; _context.Usuarios.Remove(e); await _context.SaveChangesAsync(); return true;} 
 public async Task<UsuarioResponseDto?> LoginAsync(LoginDto dto){ var e=await _context.Usuarios.Include(x=>x.Rol).FirstOrDefaultAsync(x=>x.Correo==dto.Correo); if(e==null||!PasswordHasher.Verify(dto.Contrasena,e.Contrasena)||!string.Equals(e.Estado,"activo",StringComparison.OrdinalIgnoreCase)) return null; return _mapper.Map<UsuarioResponseDto>(e);} }
